// Generated by Wrangler
// Interface definition for Cloudflare Workers AI bindings

interface Env {
  AI: {
    run(
      model: '@cf/llava-hf/llava-1.5-7b-hf' | string,
      inputs: {
        image: number[] | Uint8Array;
        prompt: string;
        max_tokens?: number;
      }
    ): Promise<{ description?: string; response?: string } | Record<string, unknown>>;
  };
  ASSETS?: {
    fetch(request: Request): Promise<Response>;
  };
}
